POST http://localhost:3000/reports/create
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 2018,
    "mileage": 12000,
    "lng": 0,
    "lat": 0,
    "salePrice": 8000
}